import Header from './components/Header'
import './globals.css'
import { Poppins } from 'next/font/google'

const poppins = Poppins({
  weight: ['400', '700'],
  subsets: ['latin'],
})

export const metadata = {
  title: 'NextJs App',
  description: 'Generated by create next app',
  keywirds: 'web development, web design, nextjs 13, react, JSX, javascript, nodejs, mongoose, mongodb, html, css'
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Header />
        <main className='container'>
          {children}
        </main>        
      </body>
    </html>
  )
}
